name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Configure Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker containers
      run: docker-compose build

    - name: Execute tests
      run: |
        mkdir qr_images
        docker-compose up -d
        pytest -v --disable-warnings
